name: "Staging: Build, Push & Deploy"

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: "Dockerfile"
            repository: "dd-rum-proxy-stag"

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build, tag, and push image to GCP Artifact Registry
      env:
        ARTIFACT_REGISTRY: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        REPOSITORY_NAME: ${{ matrix.repository }}
      run: |
        docker build -t $ARTIFACT_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG . -f ${{ matrix.dockerfile }}
        docker push $ARTIFACT_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG

    - name: Deploy Datadog RUM Proxy
      id: qovery-deploy-proxy
      env:
        QOVERY_CLI_ACCESS_TOKEN: ${{ secrets.QOVERY_CLI_ACCESS_TOKEN }}
      run: |
        # Download and install Qovery CLI
        curl -s https://get.qovery.com | bash
        # Deploy to Staging Container
        qovery container deploy \
            --organization "Meroku" \
            --project "xyz.fereai" \
            --environment "Staging" \
            --container "dd-rum-proxy" \
            --tag "${GITHUB_SHA}" \
            --watch

    - name: Clean up old images from GCP Artifact Registry
      env:
        GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        REPOSITORY_NAME: ${{ matrix.repository }}
        ARTIFACT_REGISTRY_REPO: ${{ vars.GCP_REPOSITORY }}
        GCP_REGION: ${{ vars.GCP_REGION }}
      run: |
        ls -lash ${{ github.workspace }}
        ${{ github.workspace }}/scripts/clean_old_images.sh